### ISSUE TITLE
SIGSEV error

### ISSUE THREAD

**Issue by linuxmaniac** [pcasteran/ghcr-cleaning-action#54]
```
Run pcasteran/ghcr-cleaning-action@v1
/usr/bin/docker run --name e1eeb76d539a788a20431088344cd33d024278_562199 --label e1eeb7 --workdir /github/workspace --rm -e "INPUT_PASSWORD" -e "INPUT_PACKAGE" -e "INPUT_DRY-RUN" -e "INPUT_DEBUG" -e "INPUT_REGISTRY" -e "INPUT_USER" -e "INPUT_REPOSITORY" -e "INPUT_PR-TAG-REGEX" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/kamailio/kamailio":"/github/workspace" e1eeb7:6d539a788a20431088344cd33d024278  "--registry=ghcr.io" "--user=kamailio" "--***" "--package=pkg-kamailio-docker" "--repository=kamailio/kamailio" "--pr-tag-regex=^pr-(\d+).*" "--dry-run=true" "--debug=true"
2:28PM DBG listing all the package versions package=pkg-kamailio-docker user=kamailio
2:28PM DBG fetching the container registry objects repository=ghcr.io/kamailio/pkg-kamailio-docker
2:28PM TRC fetching container registry object hash=sha256:fb192a01c8404d08226f2e8946d397596f4086e0b03e822ff4fb478370f7cc1b
2:28PM TRC fetching container registry object hash=sha256:3a5fa0aefcb8b50a8a813ee8fc74831de68b0c6f7f598ee661902c8bfcd9a417
2:28PM TRC fetching container registry object hash=sha256:2d6d344a79494ff4cfe29aa1f4320f83cb46616b722da66dd4cc4e51789b24b8
2:28PM TRC fetching container registry object hash=sha256:973b915b3c38ea292d748dabfeab66bac38ba03ef5048efb06ad2c2f8a68d271
2:28PM TRC fetching container registry object hash=sha256:099188dcfebefe9e2ab5fb22d807d182e4d87907ce8324cdd8d474ad13fff576
2:28PM TRC fetching container registry object hash=sha256:d4b98bfd48bd10740f2051cd45b645683b01c36bc762691ee70ae0c89ffb0131
2:28PM TRC fetching container registry object hash=sha256:b831d2c625552ee23552d4242151d49af9c7a0c43b619122bcd2db148fc961ad
2:28PM TRC fetching container registry object hash=sha256:f9e08e97bad46fb7fe674f6fde22aa7918d760ab87ef71759f7fadf96be35d6c
2:28PM TRC fetching container registry object hash=sha256:8f74c3846125170f7131e7949b69e780fcbc4d163bc7098694c6f5ca45dac9bf
2:28PM TRC fetching container registry object hash=sha256:341ecc9f81f4f5e86a83f6ed3ad09ac586cc3190a5562e980e143b48499e5d65
2:28PM TRC fetching container registry object hash=sha256:8a6cfd1daa4[11](https://github.com/kamailio/kamailio/actions/runs/7585093933/job/20660182921#step:3:12)a470d9fa4dda42e040f977831f9abb785dccbcabadf796f71b6
2:28PM TRC fetching container registry object hash=sha256:5875b7a50544aabb0781849caea1e762d3009bb5a86af09716f56ed29c47220a
2:28PM TRC fetching container registry object hash=sha256:a5654033542ae9f685a29aac9b76cbce757f91625e8d51c86e37b1af9d1f68c6
2:28PM TRC fetching container registry object hash=sha256:ba7c4fd7a5a6aee01ffc6487974c764cb5861d6516a28a034300e21ae9a33662
2:28PM TRC fetching container registry object hash=sha256:358088942446bdf0c32af2c9378aef0b360fd5c9cbce33d90eb3f095dbd14391
2:28PM TRC fetching container registry object hash=sha256:b31815e8a2bb7ca224bb81aa9fb389205675e10fa59607c4857fc936ae926b78
2:28PM TRC fetching container registry object hash=sha256:dd7f8e77b42ddde24982c2d69e0ed569ee19e7cb8dc2843aa58e2cfa2b79c497
2:28PM TRC fetching container registry object hash=sha256:ca1a4505106c1823d9d22fdcdddb832ccb5daa9250c9b1efd5604cb2f53d42cc
2:28PM TRC fetching container registry object hash=sha256:75d02e7cdd66fc543cb6b389c3fb1e688009b9fa4b516094fbe405f88ad3388d
2:28PM TRC fetching container registry object hash=sha256:ef9650dcdd6f8de7ce4dda7802487ebba73a205dab51894be8276b278c87f7ab
2:28PM TRC fetching container registry object hash=sha256:98d1e687f9582234e3b5f07df6ce07918f900a73258984141ad49a76bcb8c16b
2:28PM TRC fetching container registry object hash=sha256:ae238167021c38ef514723f8f6bffb3992b0e84ed872614fda806aa58f4e2b61
2:28PM TRC fetching container registry object hash=sha256:b97c475bc4babb53b11395a142daea76f340f5076224231f3289403f39324435
2:28PM TRC fetching container registry object hash=sha256:1c2ee450b9d828ef1ffdf23f98a22f4cc14f9caac6ce84a817[12](https://github.com/kamailio/kamailio/actions/runs/7585093933/job/20660182921#step:3:13)e7f70ea02055
2:28PM TRC fetching container registry object hash=sha256:e955fee11dd178a16ca61dbf00aaf2e5c4e985b576f11967a986447108b9593d
2:28PM TRC fetching container registry object hash=sha256:21406c5d28cb6b1d81a2a067b5caef2033bbe7ff80f44ee867fae40e5680a3ba
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c367d]

goroutine 1 [running]:
github.com/pcasteran/ghcr-cleaning-action/pkg.computeHashesToDelete({0xa[13](https://github.com/kamailio/kamailio/actions/runs/7585093933/job/20660182921#step:3:14)6c0, 0xc00011c1e0}, {{0x7ffdb0189eb1, 0x8}, {0x7ffdb0189eba, 0x8}, 0xc00012bae0}, 0x1000000000009?, 0xc00013d5b0?, 0xc000559638)
	/build/pkg/cleaning.go:[15](https://github.com/kamailio/kamailio/actions/runs/7585093933/job/20660182921#step:3:16)0 +0x9fd
github.com/pcasteran/ghcr-cleaning-action/pkg.Clean({0xa136c0, 0xc00011c1e0}, {{0x7ffdb0189eb1, 0x8}, {0x7ffdb0189eba, 0x8}, 0xc00012bae0}, {0xa11c38, 0xc00010d1a0}, {{0x7ffdb0189e3a, ...}, ...}, ...)
	/build/pkg/cleaning.go:67 +0x70c
github.com/pcasteran/ghcr-cleaning-action/cmd.doExecute(0xd22620?, {0x9529e0?, 0x8?, 0x8?})
	/build/cmd/root.go:95 +0x4d3
github.com/spf13/cobra.(*Command).execute(0xd22620, {0xc000126010, 0x8, 0x8})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xd22620)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/pcasteran/ghcr-cleaning-action/cmd.Execute()
	/build/cmd/root.go:49 +0x25
main.main()
	/build/main.go:8 +0x[17](https://github.com/kamailio/kamailio/actions/runs/7585093933/job/20660182921#step:3:18)
```

**Comment by linuxmaniac** [comment]
This is the workflow file:
```
---
name: cleanup packages
on:
  schedule:
    - cron: '0 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  x86_64:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        image_name:
          - kamailio
          - kamailio-ci
          - kamailio-master-devcontainer
          - pkg-kamailio-docker
    steps:
    - name: purge packages
      uses: pcasteran/ghcr-cleaning-action@v1
      with:
        password: ${{ secrets.CLEAN_PACKAGES }}
        package: ${{ matrix.image_name }}
        dry-run: true
        debug: true
```
